# Run this Dockerfile at the root of the workspace.

FROM node:22-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN npm install -g pnpm

FROM base AS build

ARG BETTER_AUTH_SECRET
ARG BETTER_AUTH_URL
ARG CHECKOUT_URL
ARG EXAMPLE_BACKEND_PORT
ARG FROM_EMAIL
ARG FROM_NAME
ARG POSTGRES_DB
ARG POSTGRES_PASSWORD
ARG POSTGRES_PORT
ARG POSTGRES_USER
ARG PSP_API_URL
ARG REDIS_PASSWORD
ARG REDIS_PORT
ARG RESEND_API_KEY
ARG RIPSTE_API_EMAIL
ARG RIPSTE_API_PASSWORD
ARG RIPSTE_API_URL
ARG SUPPORT_EMAIL
ARG VITE_API_URL
ARG VITE_EXAMPLE_BACKEND_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPABASE_URL

ENV BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET
ENV BETTER_AUTH_URL=$BETTER_AUTH_URL
ENV CHECKOUT_URL=$CHECKOUT_URL
ENV EXAMPLE_BACKEND_PORT=$EXAMPLE_BACKEND_PORT
ENV FROM_EMAIL=$FROM_EMAIL
ENV FROM_NAME=$FROM_NAME
ENV POSTGRES_DB=$POSTGRES_DB
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_PORT=$POSTGRES_PORT
ENV POSTGRES_USER=$POSTGRES_USER
ENV PSP_API_URL=$PSP_API_URL
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV REDIS_PORT=$REDIS_PORT
ENV RESEND_API_KEY=$RESEND_API_KEY
ENV RIPSTE_API_EMAIL=$RIPSTE_API_EMAIL
ENV RIPSTE_API_PASSWORD=$RIPSTE_API_PASSWORD
ENV RIPSTE_API_URL=$RIPSTE_API_URL
ENV SUPPORT_EMAIL=$SUPPORT_EMAIL
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_EXAMPLE_BACKEND_URL=$VITE_EXAMPLE_BACKEND_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL

WORKDIR /app

COPY . .

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build

RUN for dir in apps/* packages/* example; do \
  if [ -d "$dir" ]; then \
    name=$(basename "$dir"); \
    pnpm deploy --filter="${name}" --prod "/prod/${name}" --legacy; \
  fi \
done
RUN pnpm deploy --filter="@ripste/example-backend" --prod "/prod/example-backend" --legacy

FROM base AS api

WORKDIR /app

COPY --from=build /prod/api .

ENV API_PORT=3000
EXPOSE $API_PORT

ENTRYPOINT ["pnpm", "run"]
CMD ["start"]

FROM base AS psp-api

WORKDIR /app

COPY --from=build /prod/psp-api .

ENV PSP_API_PORT=3001
EXPOSE $PSP_API_PORT

ENTRYPOINT ["pnpm", "run"]
CMD ["start"]

FROM base AS checkout-page

WORKDIR /app

COPY --from=build /prod/checkout-page .

ENV CHECKOUT_PAGE_PORT=3002
EXPOSE $CHECKOUT_PAGE_PORT

ENTRYPOINT ["pnpm", "run"]
CMD ["start"]

FROM base AS admin-dashboard

WORKDIR /app

COPY --from=build /prod/admin-dashboard .

ENV ADMIN_DASHBOARD_PORT=3003
EXPOSE $ADMIN_DASHBOARD_PORT

ENTRYPOINT ["pnpm", "run"]
CMD ["start"]

FROM base AS example

WORKDIR /app

COPY --from=build /prod/example .

ENV EXAMPLE_PORT=3004
EXPOSE $EXAMPLE_PORT

ENTRYPOINT ["pnpm", "run"]
CMD ["start"]

FROM base AS example-backend

WORKDIR /app

COPY --from=build /prod/example-backend .

ENV EXAMPLE_API_PORT=3005
EXPOSE $EXAMPLE_API_PORT

ENTRYPOINT ["pnpm", "run"]
CMD ["start"]
