import type { ICheckoutPageRepository } from "./repositories/ICheckoutPageRepository.ts";
import type { ICheckoutThemeRepository } from "./repositories/ICheckoutThemeRepository.ts";
import type { ICompanyRepository } from "./repositories/ICompanyRepository.ts";
import type { IOAuthApplicationRepository } from "./repositories/IOAuthApplicationRepository.ts";
import type { IOAuthAccessTokenRepository } from "./repositories/IOAuthAccessTokenRepository.ts";
import type { IOAuthConsentRepository } from "./repositories/IOAuthConsentRepository.ts";
import type { IPaymentAttemptRepository } from "./repositories/IPaymentAttemptRepository.ts";
import type { IRefundRepository } from "./repositories/IRefundRepository.ts";
import type { IStoreMemberRepository } from "./repositories/IStoreMemberRepository.ts";
import type { IStoreRepository } from "./repositories/IStoreRepository.ts";
import type { IStoreStatusRepository } from "./repositories/IStoreStatusRepository.ts";
import type { IThemeCustomizationRepository } from "./repositories/IThemeCustomizationRepository.ts";
import type { ITransactionEventRepository } from "./repositories/ITransactionEventRepository.ts";
import type { ITransactionRepository } from "./repositories/ITransactionRepository.ts";
import type { IUserProfileRepository } from "./repositories/IUserProfileRepository.ts";
import type { IUserRepository } from "./repositories/IUserRepository.ts";
import type { ISessionRepository } from "./repositories/ISessionRepository.ts";
import type { IAccountRepository } from "./repositories/IAccountRepository.ts";
import type { IVerificationRepository } from "./repositories/IVerificationRepository.ts";

export interface IDatabase {
	checkoutPage: ICheckoutPageRepository;
	checkoutTheme: ICheckoutThemeRepository;
	company: ICompanyRepository;
	oauthApplication: IOAuthApplicationRepository;
	oauthAccessToken: IOAuthAccessTokenRepository;
	oauthConsent: IOAuthConsentRepository;
	paymentAttempt: IPaymentAttemptRepository;
	refund: IRefundRepository;
	storeMember: IStoreMemberRepository;
	store: IStoreRepository;
	storeStatus: IStoreStatusRepository;
	themeCustomization: IThemeCustomizationRepository;
	transactionEvent: ITransactionEventRepository;
	transaction: ITransactionRepository;
	userProfile: IUserProfileRepository;
	user: IUserRepository;
	session: ISessionRepository;
	account: IAccountRepository;
	verification: IVerificationRepository;
}
