name: ripste-dev

services:
  postgres:
    env_file:
      - path: ../.env.dev
        required: false
    ports: ["${POSTGRES_PORT:-5432}:5432"]

  redis:
    env_file:
      - path: ../.env.dev
        required: false
    ports: ["${REDIS_PORT:-6379}:6379"]
