services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
      - tempo
    configs:
      - source: grafana_datasources
        target: /etc/grafana/provisioning/datasources/datasources.yml

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_config:/etc/prometheus/
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"  # Tempo HTTP
      - "4317:4317"  # OTLP gRPC
    command: ["-config.file=/etc/tempo.yaml"]
    configs:
      - source: tempo_config
        target: /etc/tempo.yaml

volumes:
  grafana_provisioning:
  prometheus_config:

configs:
  grafana_datasources:
    content: |
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus:9090
          isDefault: true
        - name: Loki
          type: loki
          access: proxy
          url: http://loki:3100
        - name: Tempo
          type: tempo
          access: proxy
          url: http://tempo:3200

  prometheus_config:
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']

  tempo_config:
    content: |
      server:
        http_listen_port: 3200
        grpc_listen_port: 4317

      distributor:
        receivers:
          otlp:
            protocols:
              grpc:

      storage:
        trace:
          backend: local
          local:
            path: /tmp/tempo/traces
