services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
      - ./docker/service-configs/grafana.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
      - tempo

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./docker/service-configs/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - tempo_data:/var/tempo
      - ./docker/service-configs/tempo.yml:/etc/tempo.yaml

volumes:
  grafana_provisioning:
  grafana_data:
  tempo_data:
  prometheus_data:
  loki_data:
