services:
  grafana:
    build:
      context: .
      dockerfile: docker/dockerfiles/grafana.dockerfile
    container_name: grafana
    volumes:
      - grafana_provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
      - tempo

  prometheus:
    build:
      context: .
      dockerfile: docker/dockerfiles/prometheus.dockerfile
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus

  loki:
    build:
      context: .
      dockerfile: docker/dockerfiles/loki.dockerfile
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki

  tempo:
    build:
      context: .
      dockerfile: docker/dockerfiles/tempo.dockerfile
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - tempo_data:/var/tempo

volumes:
  grafana_provisioning:
  grafana_data:
  tempo_data:
  prometheus_data:
  loki_data:
