name: ripste-prod

services:
  api:
    build:
      context: ..
      dockerfile: apps/api/dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    env_file:
      - path: ../.env
        required: false
