name: ripste-prod

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
      target: api
      args:
          BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
          BETTER_AUTH_URL: ${BETTER_AUTH_URL}
          CHECKOUT_URL: ${CHECKOUT_URL}
          EXAMPLE_BACKEND_PORT: ${EXAMPLE_BACKEND_PORT}
          FROM_EMAIL: ${FROM_EMAIL}
          FROM_NAME: ${FROM_NAME}
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_USER: ${POSTGRES_USER}
          PSP_API_URL: ${PSP_API_URL}
          REDIS_PASSWORD: ${REDIS_PASSWORD}
          REDIS_PORT: ${REDIS_PORT}
          RESEND_API_KEY: ${RESEND_API_KEY}
          RIPSTE_API_EMAIL: ${RIPSTE_API_EMAIL}
          RIPSTE_API_PASSWORD: ${RIPSTE_API_PASSWORD}
          RIPSTE_API_URL: ${RIPSTE_API_URL}
          SUPPORT_EMAIL: ${SUPPORT_EMAIL}
          VITE_API_URL: ${VITE_API_URL}
          VITE_EXAMPLE_BACKEND_URL: ${VITE_EXAMPLE_BACKEND_URL}
          VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
          VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      CHECKOUT_URL: ${CHECKOUT_URL}
      EXAMPLE_BACKEND_PORT: ${EXAMPLE_BACKEND_PORT}
      FROM_EMAIL: ${FROM_EMAIL}
      FROM_NAME: ${FROM_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      PSP_API_URL: ${PSP_API_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RIPSTE_API_EMAIL: ${RIPSTE_API_EMAIL}
      RIPSTE_API_PASSWORD: ${RIPSTE_API_PASSWORD}
      RIPSTE_API_URL: ${RIPSTE_API_URL}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL}
      VITE_API_URL: ${VITE_API_URL}
      VITE_EXAMPLE_BACKEND_URL: ${VITE_EXAMPLE_BACKEND_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      OTLP_URL: http://tempo:4317
    env_file:
      - path: .env
        required: false

  psp:
    build:
      context: .
      dockerfile: dockerfile
      target: psp-api
      args:
          BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
          BETTER_AUTH_URL: ${BETTER_AUTH_URL}
          CHECKOUT_URL: ${CHECKOUT_URL}
          EXAMPLE_BACKEND_PORT: ${EXAMPLE_BACKEND_PORT}
          FROM_EMAIL: ${FROM_EMAIL}
          FROM_NAME: ${FROM_NAME}
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_USER: ${POSTGRES_USER}
          PSP_API_URL: ${PSP_API_URL}
          REDIS_PASSWORD: ${REDIS_PASSWORD}
          REDIS_PORT: ${REDIS_PORT}
          RESEND_API_KEY: ${RESEND_API_KEY}
          RIPSTE_API_EMAIL: ${RIPSTE_API_EMAIL}
          RIPSTE_API_PASSWORD: ${RIPSTE_API_PASSWORD}
          RIPSTE_API_URL: ${RIPSTE_API_URL}
          SUPPORT_EMAIL: ${SUPPORT_EMAIL}
          VITE_API_URL: ${VITE_API_URL}
          VITE_EXAMPLE_BACKEND_URL: ${VITE_EXAMPLE_BACKEND_URL}
          VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
          VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      CHECKOUT_URL: ${CHECKOUT_URL}
      EXAMPLE_BACKEND_PORT: ${EXAMPLE_BACKEND_PORT}
      FROM_EMAIL: ${FROM_EMAIL}
      FROM_NAME: ${FROM_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      PSP_API_URL: ${PSP_API_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RIPSTE_API_EMAIL: ${RIPSTE_API_EMAIL}
      RIPSTE_API_PASSWORD: ${RIPSTE_API_PASSWORD}
      RIPSTE_API_URL: ${RIPSTE_API_URL}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL}
      VITE_API_URL: ${VITE_API_URL}
      VITE_EXAMPLE_BACKEND_URL: ${VITE_EXAMPLE_BACKEND_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - path: .env
        required: false

  checkout:
    build:
      context: .
      dockerfile: dockerfile
      target: checkout-page
      args:
          BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
          BETTER_AUTH_URL: ${BETTER_AUTH_URL}
          CHECKOUT_URL: ${CHECKOUT_URL}
          EXAMPLE_BACKEND_PORT: ${EXAMPLE_BACKEND_PORT}
          FROM_EMAIL: ${FROM_EMAIL}
          FROM_NAME: ${FROM_NAME}
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_USER: ${POSTGRES_USER}
          PSP_API_URL: ${PSP_API_URL}
          REDIS_PASSWORD: ${REDIS_PASSWORD}
          REDIS_PORT: ${REDIS_PORT}
          RESEND_API_KEY: ${RESEND_API_KEY}
          RIPSTE_API_EMAIL: ${RIPSTE_API_EMAIL}
          RIPSTE_API_PASSWORD: ${RIPSTE_API_PASSWORD}
          RIPSTE_API_URL: ${RIPSTE_API_URL}
          SUPPORT_EMAIL: ${SUPPORT_EMAIL}
          VITE_API_URL: ${VITE_API_URL}
          VITE_EXAMPLE_BACKEND_URL: ${VITE_EXAMPLE_BACKEND_URL}
          VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
          VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      CHECKOUT_URL: ${CHECKOUT_URL}
      EXAMPLE_BACKEND_PORT: ${EXAMPLE_BACKEND_PORT}
      FROM_EMAIL: ${FROM_EMAIL}
      FROM_NAME: ${FROM_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      PSP_API_URL: ${PSP_API_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RIPSTE_API_EMAIL: ${RIPSTE_API_EMAIL}
      RIPSTE_API_PASSWORD: ${RIPSTE_API_PASSWORD}
      RIPSTE_API_URL: ${RIPSTE_API_URL}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL}
      VITE_API_URL: ${VITE_API_URL}
      VITE_EXAMPLE_BACKEND_URL: ${VITE_EXAMPLE_BACKEND_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - path: .env
        required: false

  admin:
    build:
      context: .
      dockerfile: dockerfile
      target: admin-dashboard
      args:
          BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
          BETTER_AUTH_URL: ${BETTER_AUTH_URL}
          CHECKOUT_URL: ${CHECKOUT_URL}
          EXAMPLE_BACKEND_PORT: ${EXAMPLE_BACKEND_PORT}
          FROM_EMAIL: ${FROM_EMAIL}
          FROM_NAME: ${FROM_NAME}
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_USER: ${POSTGRES_USER}
          PSP_API_URL: ${PSP_API_URL}
          REDIS_PASSWORD: ${REDIS_PASSWORD}
          REDIS_PORT: ${REDIS_PORT}
          RESEND_API_KEY: ${RESEND_API_KEY}
          RIPSTE_API_EMAIL: ${RIPSTE_API_EMAIL}
          RIPSTE_API_PASSWORD: ${RIPSTE_API_PASSWORD}
          RIPSTE_API_URL: ${RIPSTE_API_URL}
          SUPPORT_EMAIL: ${SUPPORT_EMAIL}
          VITE_API_URL: ${VITE_API_URL}
          VITE_EXAMPLE_BACKEND_URL: ${VITE_EXAMPLE_BACKEND_URL}
          VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
          VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      CHECKOUT_URL: ${CHECKOUT_URL}
      EXAMPLE_BACKEND_PORT: ${EXAMPLE_BACKEND_PORT}
      FROM_EMAIL: ${FROM_EMAIL}
      FROM_NAME: ${FROM_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      PSP_API_URL: ${PSP_API_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RIPSTE_API_EMAIL: ${RIPSTE_API_EMAIL}
      RIPSTE_API_PASSWORD: ${RIPSTE_API_PASSWORD}
      RIPSTE_API_URL: ${RIPSTE_API_URL}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL}
      VITE_API_URL: ${VITE_API_URL}
      VITE_EXAMPLE_BACKEND_URL: ${VITE_EXAMPLE_BACKEND_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - path: .env
        required: false

  example:
    build:
      context: .
      dockerfile: dockerfile
      target: example
      args:
          BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
          BETTER_AUTH_URL: ${BETTER_AUTH_URL}
          CHECKOUT_URL: ${CHECKOUT_URL}
          EXAMPLE_BACKEND_PORT: ${EXAMPLE_BACKEND_PORT}
          FROM_EMAIL: ${FROM_EMAIL}
          FROM_NAME: ${FROM_NAME}
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_USER: ${POSTGRES_USER}
          PSP_API_URL: ${PSP_API_URL}
          REDIS_PASSWORD: ${REDIS_PASSWORD}
          REDIS_PORT: ${REDIS_PORT}
          RESEND_API_KEY: ${RESEND_API_KEY}
          RIPSTE_API_EMAIL: ${RIPSTE_API_EMAIL}
          RIPSTE_API_PASSWORD: ${RIPSTE_API_PASSWORD}
          RIPSTE_API_URL: ${RIPSTE_API_URL}
          SUPPORT_EMAIL: ${SUPPORT_EMAIL}
          VITE_API_URL: ${VITE_API_URL}
          VITE_EXAMPLE_BACKEND_URL: ${VITE_EXAMPLE_BACKEND_URL}
          VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
          VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      CHECKOUT_URL: ${CHECKOUT_URL}
      EXAMPLE_BACKEND_PORT: ${EXAMPLE_BACKEND_PORT}
      FROM_EMAIL: ${FROM_EMAIL}
      FROM_NAME: ${FROM_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      PSP_API_URL: ${PSP_API_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RIPSTE_API_EMAIL: ${RIPSTE_API_EMAIL}
      RIPSTE_API_PASSWORD: ${RIPSTE_API_PASSWORD}
      RIPSTE_API_URL: ${RIPSTE_API_URL}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL}
      VITE_API_URL: ${VITE_API_URL}
      VITE_EXAMPLE_BACKEND_URL: ${VITE_EXAMPLE_BACKEND_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - path: .env
        required: false

  example-backend:
    build:
      context: .
      dockerfile: dockerfile
      target: example-backend
      args:
          BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
          BETTER_AUTH_URL: ${BETTER_AUTH_URL}
          CHECKOUT_URL: ${CHECKOUT_URL}
          EXAMPLE_BACKEND_PORT: ${EXAMPLE_BACKEND_PORT}
          FROM_EMAIL: ${FROM_EMAIL}
          FROM_NAME: ${FROM_NAME}
          POSTGRES_DB: ${POSTGRES_DB}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_USER: ${POSTGRES_USER}
          PSP_API_URL: ${PSP_API_URL}
          REDIS_PASSWORD: ${REDIS_PASSWORD}
          REDIS_PORT: ${REDIS_PORT}
          RESEND_API_KEY: ${RESEND_API_KEY}
          RIPSTE_API_EMAIL: ${RIPSTE_API_EMAIL}
          RIPSTE_API_PASSWORD: ${RIPSTE_API_PASSWORD}
          RIPSTE_API_URL: ${RIPSTE_API_URL}
          SUPPORT_EMAIL: ${SUPPORT_EMAIL}
          VITE_API_URL: ${VITE_API_URL}
          VITE_EXAMPLE_BACKEND_URL: ${VITE_EXAMPLE_BACKEND_URL}
          VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
          VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      CHECKOUT_URL: ${CHECKOUT_URL}
      EXAMPLE_BACKEND_PORT: ${EXAMPLE_BACKEND_PORT}
      FROM_EMAIL: ${FROM_EMAIL}
      FROM_NAME: ${FROM_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      PSP_API_URL: ${PSP_API_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RIPSTE_API_EMAIL: ${RIPSTE_API_EMAIL}
      RIPSTE_API_PASSWORD: ${RIPSTE_API_PASSWORD}
      RIPSTE_API_URL: ${RIPSTE_API_URL}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL}
      VITE_API_URL: ${VITE_API_URL}
      VITE_EXAMPLE_BACKEND_URL: ${VITE_EXAMPLE_BACKEND_URL}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    env_file:
      - path: .env
        required: false

  # Reference services from dependencies and metrics
  # Making services available in all other services
  # Making services available to reference in Coolify
  grafana:
  prometheus:
  tempo:
  loki:
  postgres:
  redis:
