name: ripste-prod

services:
  api:
    build:
      context: .
      dockerfile: dockerfile
      target: api
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    env_file:
      - path: .env
        required: false
