#!/bin/bash

if [ -f ".env" ]; then
  echo "Loading environment variables from .env"
  set -a && source .env && set +a
fi
for f in "$@"; do
  if [ -f ".env.$f" ]; then
    echo "Loading environment variables from .env.$f"
    set -a && source ".env.$f" && set +a
  fi
done

package_json_dirpath=$(pnpm prefix)
docker-compose \
  --project-directory "$package_json_dirpath" \
  $(for f in "$@"; do echo "-f docker/$f.docker-compose.yml"; done) \
  up -d --remove-orphans --build --force-recreate

# Usage example: `scripts/start-docker dependencies dev`
