#!/bin/bash

echo "Loading environment variables from .env"
set -a && source .env && set +a
for f in "$@"; do
  if [ -f ".env.$f" ]; then
    echo "Loading environment variables from .env.$f"
    set -a && source ".env.$f" && set +a
  fi
done

docker-compose $(for f in "$@"; do echo "-f docker/$f.docker-compose.yml"; done) up -d --remove-orphans

# Usage example: `scripts/start-docker dependencies dev`
