# Run this Dockerfile at the root of the workspace.

FROM node:22-slim

WORKDIR /app

RUN npm install -g pnpm

COPY package.json .
COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .
RUN pnpm install --frozen-lockfile

COPY . .

ENTRYPOINT ["pnpm", "run"]
CMD ["start"]
